// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3o_s73NUha85VBnn0yA_S5GMSqBEDDyo',
    appId: '1:291731637583:web:a2bf0ac10f8cb753a0f13a',
    messagingSenderId: '291731637583',
    projectId: 'flutter-message-sample-app',
    authDomain: 'flutter-message-sample-app.firebaseapp.com',
    storageBucket: 'flutter-message-sample-app.appspot.com',
    measurementId: 'G-ZPG3SK4RW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG068cpjPU1tTVsquYep1m4mJw3YZxQYE',
    appId: '1:291731637583:android:06d647de289f68b0a0f13a',
    messagingSenderId: '291731637583',
    projectId: 'flutter-message-sample-app',
    storageBucket: 'flutter-message-sample-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL-EJ3j7mPIPXNDwrZBwQSRz6Fx85hi9g',
    appId: '1:291731637583:ios:ad08de0bae7af5c8a0f13a',
    messagingSenderId: '291731637583',
    projectId: 'flutter-message-sample-app',
    storageBucket: 'flutter-message-sample-app.appspot.com',
    iosClientId: '291731637583-cnjag6qb3ellivl9s12sv5lkp4pasuom.apps.googleusercontent.com',
    iosBundleId: 'com.flutterMessageSample.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL-EJ3j7mPIPXNDwrZBwQSRz6Fx85hi9g',
    appId: '1:291731637583:ios:6402e2108b8517c4a0f13a',
    messagingSenderId: '291731637583',
    projectId: 'flutter-message-sample-app',
    storageBucket: 'flutter-message-sample-app.appspot.com',
    iosClientId: '291731637583-nvgtr0sji5d4vkspl12ahm0aa66qc2od.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMessageSampleApp',
  );
}
